In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Date1': ['2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20'],
    'Date2': ['2024:02:17', '2024:02:18', '2024:02:19', '2024:02:20'],
    'Date3': ['24/02/17', '24/02/18', '24/02/19', '24/02/20'],
    'Date4': ['02/17/2024', '02/18/2024', '02/19/2024', '02/20/2024'],
    'Date5': ['17-Feb-2024', '18-Feb-2024', '19-Feb-2024', '20-Feb-2024'],
    'DateTime1': ['24-02-17 13:45:30', '24-02-18 14:55:45', '24-02-19 15:30:15', '24-02-20 16:10:50'],
    'DateTime2': ['2024-02-17 13-45-30', '2024-02-18 14-55-45', '2024-02-19 15-30-15', '2024-02-20 16-10-50'],
    'DateTime3': ['02/17/2024 01:45:30 PM', '02/18/2024 02:55:45 PM', '02/19/2024 03:30:15 AM', '02/20/2024 04:10:50 AM'],
    'DateTime4': ['17 Feb 2024 13:45:30', '18 Feb 2024 14:55:45', '19 Feb 2024 15:30:15', '20 Feb 2024 16:10:50']
}

df = pd.DataFrame(data)
df.to_csv("date_data.csv", index=False)
df

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024:02:17,24/02/17,02/17/2024,17-Feb-2024,24-02-17 13:45:30,2024-02-17 13-45-30,02/17/2024 01:45:30 PM,17 Feb 2024 13:45:30
1,2024-02-18,2024:02:18,24/02/18,02/18/2024,18-Feb-2024,24-02-18 14:55:45,2024-02-18 14-55-45,02/18/2024 02:55:45 PM,18 Feb 2024 14:55:45
2,2024-02-19,2024:02:19,24/02/19,02/19/2024,19-Feb-2024,24-02-19 15:30:15,2024-02-19 15-30-15,02/19/2024 03:30:15 AM,19 Feb 2024 15:30:15
3,2024-02-20,2024:02:20,24/02/20,02/20/2024,20-Feb-2024,24-02-20 16:10:50,2024-02-20 16-10-50,02/20/2024 04:10:50 AM,20 Feb 2024 16:10:50

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date1      4 non-null      object
 1   Date2      4 non-null      object
 2   Date3      4 non-null      object
 3   Date4      4 non-null      object
 4   Date5      4 non-null      object
 5   DateTime1  4 non-null      object
 6   DateTime2  4 non-null      object
 7   DateTime3  4 non-null      object
 8   DateTime4  4 non-null      object
dtypes: object(9)
memory usage: 420.0+ bytes

In [4]:
#데이트타임으로 변경 시 명시적으로 format 형태 지정해줘야 잘못된 형태의 변경이 일어나지 않음.
df = pd.read_csv("date_data.csv")
df['Date1'] = pd.to_datetime(df['Date1'])
df['Date2'] = pd.to_datetime(df['Date2'], format='%Y:%m:%d')
df['Date3'] = pd.to_datetime(df['Date3'])
df['Date4'] = pd.to_datetime(df['Date4'])
df['Date5'] = pd.to_datetime(df['Date5'])
df['DateTime1'] = pd.to_datetime(df['DateTime1'])
df['DateTime2'] = pd.to_datetime(df['DateTime2'], format='%Y-%m-%d %H-%M-%S')
df['DateTime3'] = pd.to_datetime(df['DateTime3'])
df['DateTime4'] = pd.to_datetime(df['DateTime4'])
df

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21652\2722885956.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date3'] = pd.to_datetime(df['Date3'])
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21652\2722885956.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DateTime1'] = pd.to_datetime(df['DateTime1'])
C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_21652\2722885956.py:9: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['DateTime3'] = pd.to_datetime(df['DateTime3'])

,Date1,Date2,Date3,Date4,Date5,DateTime1,DateTime2,DateTime3,DateTime4
0,2024-02-17,2024-02-17,2017-02-24,2024-02-17,2024-02-17,2017-02-24 13:45:30,2024-02-17 13:45:30,2024-02-17 13:45:30,2024-02-17 13:45:30
1,2024-02-18,2024-02-18,2018-02-24,2024-02-18,2024-02-18,2018-02-24 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45,2024-02-18 14:55:45
2,2024-02-19,2024-02-19,2019-02-24,2024-02-19,2024-02-19,2019-02-24 15:30:15,2024-02-19 15:30:15,2024-02-19 03:30:15,2024-02-19 15:30:15
3,2024-02-20,2024-02-20,2020-02-24,2024-02-20,2024-02-20,2020-02-24 16:10:50,2024-02-20 16:10:50,2024-02-20 04:10:50,2024-02-20 16:10:50

In [8]:
df = pd.read_csv("date_data.csv")
df['Date2'] = pd.to_datetime(df['Date2'], format='%Y:%m:%d')
df['Date3'] = pd.to_datetime(df['Date3'], format='%y/%m/%d')
df['DateTime1'] = pd.to_datetime(df['DateTime1'], format='%y-%m-%d %H:%M:%S')
df['DateTime2'] = pd.to_datetime(df['DateTime2'], format='%Y-%m-%d %H-%M-%S')
df[['Date2', 'Date3', 'DateTime1', 'DateTime2']]

       Date2      Date3           DateTime1           DateTime2
0 2024-02-17 2024-02-17 2024-02-17 13:45:30 2024-02-17 13:45:30
1 2024-02-18 2024-02-18 2024-02-18 14:55:45 2024-02-18 14:55:45
2 2024-02-19 2024-02-19 2024-02-19 15:30:15 2024-02-19 15:30:15
3 2024-02-20 2024-02-20 2024-02-20 16:10:50 2024-02-20 16:10:50

In [12]:
#날짜,시간 분해
df = df[['DateTime1']] #샘플 컬럼 1개만 남김
df = df.rename(columns={'DateTime1':'datetime'}) #컬럼명 변경
df

             datetime
0 2024-02-17 13:45:30
1 2024-02-18 14:55:45
2 2024-02-19 15:30:15
3 2024-02-20 16:10:50

In [15]:
df['year'] = df['datetime'].dt.year
df['month'] = df['datetime'].dt.month
df['day'] = df['datetime'].dt.day
df['hour'] = df['datetime'].dt.hour
df['minute'] = df['datetime'].dt.minute
df['second'] = df['datetime'].dt.second
df['dayofweek'] = df['datetime'].dt.dayofweek

             datetime  year  month  day  hour  minute  second  dayofweek
0 2024-02-17 13:45:30  2024      2   17    13      45      30          5
1 2024-02-18 14:55:45  2024      2   18    14      55      45          6
2 2024-02-19 15:30:15  2024      2   19    15      30      15          0
3 2024-02-20 16:10:50  2024      2   20    16      10      50          1

In [16]:
# : map() 활용
week = {
    0:'일요일',
    1:'월요일',
    2:'화요일',
    3:'수요일',
    4:'목요일',
    5:'금요일',
    6:'토요일',
}

df['day_name'] = df['dayofweek'].map(week)
df

,datetime,year,month,day,hour,minute,second,dayofweek,day_name
0,2024-02-17 13:45:30,2024,2,17,13,45,30,5,금요일
1,2024-02-18 14:55:45,2024,2,18,14,55,45,6,토요일
2,2024-02-19 15:30:15,2024,2,19,15,30,15,0,일요일
3,2024-02-20 16:10:50,2024,2,20,16,10,50,1,월요일

In [18]:
#특정 시간과의 차이
day = pd.Timedelta(days=99)
df['100day'] = df['datetime']+ day
df

,datetime,year,month,day,hour,minute,second,dayofweek,day_name,100day
0,2024-02-17 13:45:30,2024,2,17,13,45,30,5,금요일,2024-05-26 13:45:30
1,2024-02-18 14:55:45,2024,2,18,14,55,45,6,토요일,2024-05-27 14:55:45
2,2024-02-19 15:30:15,2024,2,19,15,30,15,0,일요일,2024-05-28 15:30:15
3,2024-02-20 16:10:50,2024,2,20,16,10,50,1,월요일,2024-05-29 16:10:50

In [20]:
#시간차이 구하기
diff = df['100day'] - df['datetime']
diff

0   99 days
1   99 days
2   99 days
3   99 days
dtype: timedelta64[ns]

In [24]:
print('초 차이 :') 
print(diff.dt.total_seconds())
print('분 차이 :')
print(diff.dt.total_seconds()/60)
print('시간 차이 :')
print(diff.dt.total_seconds()/60/60)
print('일 차이 :')
print(diff.dt.total_seconds()/60/60/24)

초 차이 :
0    8553600.0
1    8553600.0
2    8553600.0
3    8553600.0
dtype: float64
분 차이 :
0    142560.0
1    142560.0
2    142560.0
3    142560.0
dtype: float64
시간 차이 :
0    2376.0
1    2376.0
2    2376.0
3    2376.0
dtype: float64
일 차이 :
0    99.0
1    99.0
2    99.0
3    99.0
dtype: float64

## 데이터프레임 병합

In [28]:
appetizer_df = pd.DataFrame({
    'Menu' : ['Salad', 'Soup', 'Bread'],
    'Price' : [5000,3000,2000]
})

main_df = pd.DataFrame({
    'Menu' : ['Steak','Pasta','Chicken'],
    'Price' : [15000,12000,10000]
})

In [33]:
#concat 기본값은 행 병합
full_menu = pd.concat([appetizer_df,main_df], ignore_index=True)
full_menu

      Menu  Price
0    Salad   5000
1     Soup   3000
2    Bread   2000
3    Steak  15000
4    Pasta  12000
5  Chicken  10000

In [34]:
#concat으로 열 병합
full_menu = pd.concat([appetizer_df, main_df], axis=1)
full_menu

    Menu  Price     Menu  Price
0  Salad   5000    Steak  15000
1   Soup   3000    Pasta  12000
2  Bread   2000  Chicken  10000

## key기준 병합

In [35]:
price = pd.DataFrame({
    'Menu' : ['Salad', 'Soup','Steak','Pasta'],
    'Price' :  [5000,3000,15000,12000]
})

cal = pd.DataFrame({
    'Menu' : ['Salad', 'Soup','Steak','Pasta'],
    'cal' : [100,500,400,150]
})

In [36]:
menu_info = pd.merge(price,cal, on='Menu')
menu_info

    Menu  Price  cal
0  Salad   5000  100
1   Soup   3000  500
2  Steak  15000  400
3  Pasta  12000  150

## 피벗테이블

In [46]:
df = pd.DataFrame({
    '이름' : ['서아','다인','채아','예담','종현','태헌'],
    '부서' : ['개발','기획','개발','기획','개발','기획'],
    '급여' : [3000,3200,3100,3300,2900,3100],
})

df

   이름  부서    급여
0  서아  개발  3000
1  다인  기획  3200
2  채아  개발  3100
3  예담  기획  3300
4  종현  개발  2900
5  태헌  기획  3100

In [47]:
pt = df.pivot_table(index='부서', values='급여', aggfunc='mean')
pt

        급여
부서
개발  3000.0
기획  3200.0

In [48]:
df = pd.DataFrame({
    '부서' : ['개발','기획','기획','기획','개발','개발'],
    '직급' : ['대리','과장','대리','과장','대리','과장'],
    '급여' : [3000,4000,3200,4200,3500,4500],
})
df

   부서  직급    급여
0  개발  대리  3000
1  기획  과장  4000
2  기획  대리  3200
3  기획  과장  4200
4  개발  대리  3500
5  개발  과장  4500

In [49]:
pt = df.pivot_table(index='부서', columns='직급', values='급여', aggfunc='sum')
pt

직급    과장    대리
부서
개발  4500  6500
기획  8200  3200

In [51]:
df = pd.DataFrame({
    "구분": ["전자", "전자", "전자", "전자", "전자", "가전", "가전", "가전", "가전"],
    "유형": ["일반", "일반", "일반", "특수", "특수", "일반", "일반", "특수", "특수"],
    "크기": ["소형", "대형", "대형", "소형", "소형", "대형", "소형", "소형", "대형"],
    "수량": [1, 2, 2, 3, 3, 4, 5, 6, 7],
    "금액": [2, 4, 5, 5, 6, 6, 8, 9, 9]
})
df

   구분  유형  크기  수량  금액
0  전자  일반  소형   1   2
1  전자  일반  대형   2   4
2  전자  일반  대형   2   5
3  전자  특수  소형   3   5
4  전자  특수  소형   3   6
5  가전  일반  대형   4   6
6  가전  일반  소형   5   8
7  가전  특수  소형   6   9
8  가전  특수  대형   7   9

In [55]:
pt = pd.pivot_table(
    df,
    index=['구분','유형'],
    values='수량',
    columns=['크기'],
    aggfunc='sum',
    fill_value=0
)
pt

크기     대형  소형
구분 유형
가전 일반   4   5
   특수   7   6
전자 일반   4   1
   특수   0   6

In [58]:
#여러 열에 대해 각기 다른 집계 함수 사용
pt = pd.pivot_table(
    df,
    values=['수량','금액'],
    index=['구분','크기'],
    aggfunc={'수량':'mean', '금액':['min','max','mean']}
)

pt

       금액                      수량
      max      mean min      mean
구분 크기
가전 대형   9  7.500000   6  5.500000
   소형   9  8.500000   8  5.500000
전자 대형   5  4.500000   4  2.000000
   소형   6  4.333333   2  2.333333

In [59]:
pt=pt.reset_index()
pt

   구분  크기  금액                      수량
          max      mean min      mean
0  가전  대형   9  7.500000   6  5.500000
1  가전  소형   9  8.500000   8  5.500000
2  전자  대형   5  4.500000   4  2.000000
3  전자  소형   6  4.333333   2  2.333333