In [34]:
import pandas as pd
import numpy as numpy

In [35]:
df = pd.DataFrame({
    "A" : ["데이터 분석", "기본 학습서", "퇴근 후 열공"],
    "B" : [10,20,30],
    "C" : ["ab cd", "AB CD", "ab cd"]
})

df

         A   B      C
0   데이터 분석  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [36]:
#문자열 변경 -  replace로만은 전체문자열 중 일부 변경은 불가
df["A"] = df["A"].replace("분석", "시각화")
df

         A   B      C
0   데이터 분석  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [37]:
df["A"] = df["A"].str.replace("분석", "시각화")
df

         A   B      C
0  데이터 시각화  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [38]:
#수치형 변경
df['B'] = df['B'].replace(10,100)
df

         A    B      C
0  데이터 시각화  100  ab cd
1   기본 학습서   20  AB CD
2  퇴근 후 열공   30  ab cd

In [39]:
#str.split()[0] vs str.split().str[0]
df['A'].str.split()[0]

['데이터', '시각화']

In [40]:
df['D'] = df['A'].str.split().str[0]
df

         A    B      C    D
0  데이터 시각화  100  ab cd  데이터
1   기본 학습서   20  AB CD   기본
2  퇴근 후 열공   30  ab cd   퇴근

In [41]:
#특정 문자열 탐색
df['A'].str.contains('기본')

0    False
1     True
2    False
Name: A, dtype: bool

In [42]:
df['기본포함여부'] = df['A'].str.contains('기본')
df

         A    B      C    D  기본포함여부
0  데이터 시각화  100  ab cd  데이터   False
1   기본 학습서   20  AB CD   기본    True
2  퇴근 후 열공   30  ab cd   퇴근   False

In [43]:
df['문자길이'] = df['A'].str.len()
df

         A    B      C    D  기본포함여부  문자길이
0  데이터 시각화  100  ab cd  데이터   False     7
1   기본 학습서   20  AB CD   기본    True     6
2  퇴근 후 열공   30  ab cd   퇴근   False     7

In [44]:
#소문자 변환
df['C'] = df['C'].str.lower()
df['C']

0    ab cd
1    ab cd
2    ab cd
Name: C, dtype: object

In [45]:
df['C'] = df['C'].str.upper()
df['C']

0    AB CD
1    AB CD
2    AB CD
Name: C, dtype: object

In [46]:
#형변환 + 문자변환
df['C'] = df['C'].str.lower()
df['C'] = df['C'].str.replace(' ', '')
df[['C']]

      C
0  abcd
1  abcd
2  abcd

## 내장함수

In [47]:
df = pd.read_csv('cafe4.csv')
df

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0
2   카페모카  5500  250   과테말라  1000.0
3   카푸치노  5000  110   과테말라     NaN
4  에스프레소  4000   20  코스타리카     NaN
5    밀크티  5900  210  코스타리카     NaN
6     녹차  5300    0   대한민국     NaN
7   딴짓라떼  2000   20  코스타리카     NaN

In [48]:
#len()
print("행 수 : ", str(len(df)))
print("행 수 : ", str(df.shape[0]))
print("열 수 : ", str(df.shape[1]))

행 수 :  8
행 수 :  8
열 수 :  5

In [49]:
#조건에 맞는 행 수
cond = df['가격'] > 5000

#sum()으로 행 수
print("sum  : ", sum(cond))
#len()으로 행 수 
print("len : ", len(df[cond]))

sum  :  3
len :  3

In [50]:
#데이터플레임의 sum(numeric_only=True) : 수치형 컬럼의 총합 반환
df.sum(numeric_only = True)

가격      37200.0
칼로리       730.0
이벤트가     2000.0
dtype: float64

#### 행과 열 변경

In [51]:
df.T

          0       1       2     3      4      5     6      7
메뉴    아메리카노    카페라떼    카페모카  카푸치노  에스프레소    밀크티    녹차   딴짓라떼
가격     4500    5000    5500  5000   4000   5900  5300   2000
칼로리      10     110     250   110     20    210     0     20
원산지    콜롬비아   코스타리카    과테말라  과테말라  코스타리카  코스타리카  대한민국  코스타리카
이벤트가    NaN  1000.0  1000.0   NaN    NaN    NaN   NaN    NaN

In [52]:
#열 방향으로 sum
df.sum(axis=1, numeric_only=True) #수치형 컬럼인 가격+칼로리값 반환

0    4510.0
1    6110.0
2    6750.0
3    5110.0
4    4020.0
5    6110.0
6    5300.0
7    2020.0
dtype: float64

In [53]:
df.describe()

                가격         칼로리    이벤트가
count     8.000000    8.000000     2.0
mean   4650.000000   91.250000  1000.0
std    1220.070256   96.427249     0.0
min    2000.000000    0.000000  1000.0
25%    4375.000000   17.500000  1000.0
50%    5000.000000   65.000000  1000.0
75%    5350.000000  135.000000  1000.0
max    5900.000000  250.000000  1000.0

In [54]:
#기초 통계값
print("최댓값 :", df['가격'].max())
print("최솟값 :", df['가격'].min())
print("평균값 :", df['가격'].mean())
print("중앙값 :", df['가격'].median())
print("합계 :", df['가격'].sum())
print("표준편차 :", df['가격'].std())
print("분산 :", df['가격'].var())

최댓값 : 5900
최솟값 : 2000
평균값 : 4650.0
중앙값 : 5000.0
합계 : 37200
표준편차 : 1220.070255588353
분산 : 1488571.4285714286

In [55]:
#quantile (4분위수)

In [56]:
print('1분위수(25%) :',df['가격'].quantile(0.25))
print('중앙값(50%) :',df['가격'].quantile(0.5))
print('3분위수(75%) :',df['가격'].quantile(0.75))

1분위수(25%) : 4375.0
중앙값(50%) : 5000.0
3분위수(75%) : 5350.0

In [57]:
#1분위보다 낮은 값 찾기
cond = df['가격'].quantile(0.25) > df['가격']
df[cond]

      메뉴    가격  칼로리    원산지  이벤트가
4  에스프레소  4000   20  코스타리카   NaN
7   딴짓라떼  2000   20  코스타리카   NaN

In [58]:
#3분위보다 큰 값 찾기
cond = df['가격'].quantile(0.75) < df['가격']
df[cond]

     메뉴    가격  칼로리    원산지    이벤트가
2  카페모카  5500  250   과테말라  1000.0
5   밀크티  5900  210  코스타리카     NaN

In [59]:
df['원산지'].value_counts()

원산지
코스타리카    4
과테말라     2
콜롬비아     1
대한민국     1
Name: count, dtype: int64

In [60]:
#최빈값 찾기
df['원산지'].mode()[0] #최빈값은 1개가 아닐 수 있어서 mode()의 결과는 series이다.

'코스타리카'

In [61]:
#가격이 가장 비싼 메뉴 찾기
max_idx = df['가격'].idxmax() #idxmax()는 max값이 복수여도 1개만 반환
df.loc[max_idx]

메뉴        밀크티
가격       5900
칼로리       210
원산지     코스타리카
이벤트가      NaN
Name: 5, dtype: object

In [62]:
cond = df['가격'].max() == df['가격']
df[cond]

    메뉴    가격  칼로리    원산지  이벤트가
5  밀크티  5900  210  코스타리카   NaN

In [63]:
#가격이 가장 싼 메뉴 찾기
min_idx = df['가격'].idxmin()
df.loc[min_idx]

메뉴       딴짓라떼
가격       2000
칼로리        20
원산지     코스타리카
이벤트가      NaN
Name: 7, dtype: object

In [64]:
cond = df['가격'].min() == df['가격']
df[cond]

     메뉴    가격  칼로리    원산지  이벤트가
7  딴짓라떼  2000   20  코스타리카   NaN

In [65]:
#가장 큰 값 n만큼 반환
df.nlargest(3,"가격")

     메뉴    가격  칼로리    원산지    이벤트가
5   밀크티  5900  210  코스타리카     NaN
2  카페모카  5500  250   과테말라  1000.0
6    녹차  5300    0   대한민국     NaN

In [66]:
#가장 작은 값 n만큼 반환
df.nsmallest(3,"가격")

      메뉴    가격  칼로리    원산지  이벤트가
7   딴짓라떼  2000   20  코스타리카   NaN
4  에스프레소  4000   20  코스타리카   NaN
0  아메리카노  4500   10   콜롬비아   NaN

## apply() : 사용자 생성 함수 사용

In [67]:
def cal(x):
    if x >= 100:
        return 'No'
    else:
        return 'Yes'

In [68]:
df['먹어도 될까요'] = df['칼로리'].apply(cal)
df

      메뉴    가격  칼로리    원산지    이벤트가 먹어도 될까요
0  아메리카노  4500   10   콜롬비아     NaN     Yes
1   카페라떼  5000  110  코스타리카  1000.0      No
2   카페모카  5500  250   과테말라  1000.0      No
3   카푸치노  5000  110   과테말라     NaN      No
4  에스프레소  4000   20  코스타리카     NaN     Yes
5    밀크티  5900  210  코스타리카     NaN      No
6     녹차  5300    0   대한민국     NaN     Yes
7   딴짓라떼  2000   20  코스타리카     NaN     Yes

## melt() : 넓은 형태의 데이터를 긴 형태의 데이터로 변경
#### id_vars(필수) : 재구조 시 유지할 컬럼
#### value_vars(선택) : 재구조될 컬럼

In [74]:
df = pd.DataFrame({
    '반' : ['A반','A반','B반'],
    '이름' : ['쿼카','알파카','시바견'],
    '수학' : [90,93,85],
    '영어' : [92,84,86],
    '국어' : [91,94,83],
    
})
df

    반   이름  수학  영어  국어
0  A반   쿼카  90  92  91
1  A반  알파카  93  84  94
2  B반  시바견  85  86  83

In [76]:
melt_df = pd.melt(df,id_vars=['이름'], value_vars=['수학','영어','국어'])
melt_df

    이름 variable  value
0   쿼카       수학     90
1  알파카       수학     93
2  시바견       수학     85
3   쿼카       영어     92
4  알파카       영어     84
5  시바견       영어     86
6   쿼카       국어     91
7  알파카       국어     94
8  시바견       국어     83

In [77]:
melt_df = pd.melt(df,id_vars=['반','이름'], value_vars=['국어', '영어'], var_name = '과목', value_name='점수')
melt_df

    반   이름  과목  점수
0  A반   쿼카  국어  91
1  A반  알파카  국어  94
2  B반  시바견  국어  83
3  A반   쿼카  영어  92
4  A반  알파카  영어  84
5  B반  시바견  영어  86

## 그룹핑

In [78]:
df = pd.read_csv('cafe4.csv')
df

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0
2   카페모카  5500  250   과테말라  1000.0
3   카푸치노  5000  110   과테말라     NaN
4  에스프레소  4000   20  코스타리카     NaN
5    밀크티  5900  210  코스타리카     NaN
6     녹차  5300    0   대한민국     NaN
7   딴짓라떼  2000   20  코스타리카     NaN

In [80]:
mean_df = df.groupby(['원산지']).mean(numeric_only=True)
mean_df

           가격    칼로리    이벤트가
원산지
과테말라   5250.0  180.0  1000.0
대한민국   5300.0    0.0     NaN
코스타리카  4225.0   90.0  1000.0
콜롬비아   4500.0   10.0     NaN

## agg() : 그룹연산을 다중 선택 시

In [81]:
agg_df = df.groupby(['원산지','메뉴']).agg(['mean','sum'])
agg_df

                 가격          칼로리         이벤트가
               mean   sum   mean  sum    mean     sum
원산지   메뉴
과테말라  카페모카   5500.0  5500  250.0  250  1000.0  1000.0
      카푸치노   5000.0  5000  110.0  110     NaN     0.0
대한민국  녹차     5300.0  5300    0.0    0     NaN     0.0
코스타리카 딴짓라떼   2000.0  2000   20.0   20     NaN     0.0
      밀크티    5900.0  5900  210.0  210     NaN     0.0
      에스프레소  4000.0  4000   20.0   20     NaN     0.0
      카페라떼   5000.0  5000  110.0  110  1000.0  1000.0
콜롬비아  아메리카노  4500.0  4500   10.0   10     NaN     0.0

In [82]:
#인덱스 재설정
agg_df = agg_df.reset_index()
agg_df

     원산지     메뉴      가격          칼로리         이벤트가
                   mean   sum   mean  sum    mean     sum
0   과테말라   카페모카  5500.0  5500  250.0  250  1000.0  1000.0
1   과테말라   카푸치노  5000.0  5000  110.0  110     NaN     0.0
2   대한민국     녹차  5300.0  5300    0.0    0     NaN     0.0
3  코스타리카   딴짓라떼  2000.0  2000   20.0   20     NaN     0.0
4  코스타리카    밀크티  5900.0  5900  210.0  210     NaN     0.0
5  코스타리카  에스프레소  4000.0  4000   20.0   20     NaN     0.0
6  코스타리카   카페라떼  5000.0  5000  110.0  110  1000.0  1000.0
7   콜롬비아  아메리카노  4500.0  4500   10.0   10     NaN     0.0

## transform()을 사용한 평균값 결측치 채우기
#### transform 통계함수 : mean(평균), sum(합계), 최댓값(max), 최솟값(min), 중앙값(median), 최빈값(mode)

In [84]:
df = pd.DataFrame({
    '과일' : ['딸기', '블루베리','딸기', '블루베리','딸기', '블루베리','딸기', '블루베리'],
    '가격' : [1000, None, 1500, None, 2000, 2500, None, 1800],
})
df

     과일      가격
0    딸기  1000.0
1  블루베리     NaN
2    딸기  1500.0
3  블루베리     NaN
4    딸기  2000.0
5  블루베리  2500.0
6    딸기     NaN
7  블루베리  1800.0

In [93]:
#transform()을 사용한 평균값 결측치 채우기
mean_price = df.groupby("과일")['가격'].transform("mean")
df['가격'] = df['가격'].fillna(mean_price)
df

     과일      가격
0    딸기  1000.0
1  블루베리  2150.0
2    딸기  1500.0
3  블루베리  2150.0
4    딸기  2000.0
5  블루베리  2500.0
6    딸기  1500.0
7  블루베리  1800.0

In [95]:
# 다중 그룹핑 조건
df = pd.DataFrame({
    '과일' : ['딸기', '블루베리','딸기', '블루베리','딸기', '블루베리','딸기', '블루베리'],
    '등급' : ['B','B','A','A', 'A', 'A', 'B', 'B'],
    '가격' : [1000, None, 1500, None, 2000, 2500, None, 1800],
})
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B     NaN
2    딸기  A  1500.0
3  블루베리  A     NaN
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B     NaN
7  블루베리  B  1800.0

In [96]:
mean_price = df.groupby(['과일','등급'])['가격'].transform('mean')
mean_price

0    1000.0
1    1800.0
2    1750.0
3    2500.0
4    1750.0
5    2500.0
6    1000.0
7    1800.0
Name: 가격, dtype: float64

In [97]:
df['가격'] = df['가격'].fillna(mean_price)
df

     과일 등급      가격
0    딸기  B  1000.0
1  블루베리  B  1800.0
2    딸기  A  1500.0
3  블루베리  A  2500.0
4    딸기  A  2000.0
5  블루베리  A  2500.0
6    딸기  B  1000.0
7  블루베리  B  1800.0

## unstack() : 다중인덱스에서 특정 인덱스를 컬럼으로 전환

In [98]:
coffee_df = pd.DataFrame({
    '커피':['아메리카노','아메리카노','아메리카노','라떼','라떼','라떼'],
    '컵크기':['Small','Medium','Large','Small','Medium','Large'],
    '판매량':[120,150,200,100,130,180],
})
coffee_df

      커피     컵크기  판매량
0  아메리카노   Small  120
1  아메리카노  Medium  150
2  아메리카노   Large  200
3     라떼   Small  100
4     라떼  Medium  130
5     라떼   Large  180

In [111]:
grouped = coffee_df.groupby(['커피','컵크기'])['판매량'].sum()
grouped = grouped.to_frame()

              판매량
커피    컵크기
라떼    Large   180
      Medium  130
      Small   100
아메리카노 Large   200
      Medium  150
      Small   120

In [112]:
grouped1 = grouped.unstack() #level = -1(마지막 인덱스)가 기본값
grouped1

컵크기    Large  Medium  Small
커피
라떼       180     130    100
아메리카노    200     150    120

In [114]:
grouped2 = grouped.unstack(level=0) #첫번째 인덱스를 컬럼으로 전환
grouped2

커피       라떼  아메리카노
컵크기
Large   180    200
Medium  130    150
Small   100    120