In [35]:
import numpy as np
import pandas as pd

## Q1 ~ Q10

In [36]:
df = pd.DataFrame({
    '메뉴' : ['아메리카노','커페라떼','에스프레소','카페모카','바닐라라떼'],
    '가격' : [4500,5000,4000,5900,5300],
    '칼로리' : [10,110, np.nan, 210, np.nan],
    '원두' : ['과테말라', '브라질', '과테말라', np.nan, np.nan]
})
df

      메뉴    가격    칼로리    원두
0  아메리카노  4500   10.0  과테말라
1   커페라떼  5000  110.0   브라질
2  에스프레소  4000    NaN  과테말라
3   카페모카  5900  210.0   NaN
4  바닐라라떼  5300    NaN   NaN

#### Q1.'칼로리' 컬럼의 결측치를 칼로리 데이터 중 최솟값으로 채우시오.

In [37]:
min_col = df['칼로리'].min()
df['칼로리'] = df['칼로리'].fillna(min_col)
df

      메뉴    가격    칼로리    원두
0  아메리카노  4500   10.0  과테말라
1   커페라떼  5000  110.0   브라질
2  에스프레소  4000   10.0  과테말라
3   카페모카  5900  210.0   NaN
4  바닐라라떼  5300   10.0   NaN

#### Q2.'원두' 컬럼의 결측치를 '원두'데이터 중 최빈값으로 채우시오.

In [38]:
mode = df['원두'].mode()[0]
df['원두'] = df['원두'].fillna(mode)
df

      메뉴    가격    칼로리    원두
0  아메리카노  4500   10.0  과테말라
1   커페라떼  5000  110.0   브라질
2  에스프레소  4000   10.0  과테말라
3   카페모카  5900  210.0  과테말라
4  바닐라라떼  5300   10.0  과테말라

#### Q3.가격이 5,000 이상인 데이터의 수를 구하시오.

In [39]:
cond = df['가격'] >= 5000
print("sum 사용 :", sum(cond))
print("len 사용 :", len(df[cond]))

sum 사용 : 3
len 사용 : 3

#### Q4.'이벤트가' 컬럼을 만들고 기존 가격에서 50% 할인된 가격을 채우시오.

In [40]:
discount = 0.5
df['이벤트가'] = df['가격'] * (1-discount)
df['이벤트가'] = df['이벤트가'].astype('int')
df

      메뉴    가격    칼로리    원두  이벤트가
0  아메리카노  4500   10.0  과테말라  2250
1   커페라떼  5000  110.0   브라질  2500
2  에스프레소  4000   10.0  과테말라  2000
3   카페모카  5900  210.0  과테말라  2950
4  바닐라라떼  5300   10.0  과테말라  2650

#### Q5.'칼로리' 컬럼을 삭제하시오.

In [41]:
df = df.drop('칼로리', axis=1)
df

      메뉴    가격    원두  이벤트가
0  아메리카노  4500  과테말라  2250
1   커페라떼  5000   브라질  2500
2  에스프레소  4000  과테말라  2000
3   카페모카  5900  과테말라  2950
4  바닐라라떼  5300  과테말라  2650

#### Q6.위에서부터 3개의 행만 선택하시오.(loc사용)

In [42]:
df.loc[:2]

      메뉴    가격    원두  이벤트가
0  아메리카노  4500  과테말라  2250
1   커페라떼  5000   브라질  2500
2  에스프레소  4000  과테말라  2000

#### Q7.위에서부터 3개의 행만 선택하시오.(iloc사용)

In [43]:
df.iloc[:3]

      메뉴    가격    원두  이벤트가
0  아메리카노  4500  과테말라  2250
1   커페라떼  5000   브라질  2500
2  에스프레소  4000  과테말라  2000

#### Q8.주어진 데이터(df)에서 아래의 값이 나오도록 loc를 활용해 데이터프레임으로 출력하시오.
#### 카페라떼   5000
#### 에스프레소 4000

In [44]:
df.loc[1:2, '메뉴' : '가격']

      메뉴    가격
1   커페라떼  5000
2  에스프레소  4000

#### Q8.주어진 데이터(df)에서 아래의 값이 나오도록 iloc를 활용해 데이터프레임으로 출력하시오.
#### 카페라떼   5000
#### 에스프레소 4000

In [45]:
df.iloc[1:3,0:2]

      메뉴    가격
1   커페라떼  5000
2  에스프레소  4000

#### Q10.메뉴 중 가격이 가장 비싼 순으로 정렬해 상위 3개의 값을 구하시오.

In [49]:
df = df.sort_values('가격', ascending=False)
df.iloc[0:3]

#정렬을 하라고 했음으로 df.nlargest(3,'가격')이 아닌 sort_values('가격', ascending=Fale) 후 3행까지 출력하여야 한다.

      메뉴    가격    원두  이벤트가
3   카페모카  5900  과테말라  2950
4  바닐라라떼  5300  과테말라  2650
1   커페라떼  5000   브라질  2500