In [1]:
import numpy as np
import pandas as pd

## S11.슬라이싱, 사분위수, 결측치 제거

In [7]:
df = pd.read_csv('type1_data1.csv')
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.데이터에서 결측치가 있는 데이터(행)을 모두 제거하시오.

In [8]:
df = df.dropna()
print("행 수 :", len(df))

행 수 : 70

#### 2.결측치가 제거된 데이터를 사용하여 앞에서부터 70% 데이터를 구하시오.
#### (단, 데이터 70 % 지점의 index가 소수점으로 계산될 경우 소수점 이하는 버림)

In [9]:
end = int(len(df) * 0.7)
df = df.iloc[:end]

print("행 수 :", len(df))
df.head()

행 수 : 49

       id   age city     f1  f2      f3    f4         f5  subscribed    views
2    id03  27.0   서울   61.0   1    gold  ISTJ  17.252986  2024-03-16   7312.0
5    id06  22.0   서울   57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
7    id08  38.0   서울  101.0   1  silver  INFJ  83.685380  2024-03-06   3260.0
9    id10  95.0   서울   74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
10  id100  47.0   경기   53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0

#### 앞에서 구한 70% 데이터 중 'views' 컬럼의 3사분위수에서 1사분위수를 뺀 값을 소수점 이하를 버리고 정수부분만 구하시오.

In [10]:
q3 = df['views'].quantile(0.75)
q1 = df['views'].quantile(0.25)

iqr = int(q3-q1)
print("IQR :", iqr)

IQR : 2771

## S12.결측치 처리, 최빈갑스 데이터 개수

In [49]:
df = pd.read_csv('type1_data1.csv')
print("행 수 :", len(df))
df.head()

행 수 : 120

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.결측치가 가장 많은 두 컬럼을 찾으시오.

In [50]:
null_series = df.isnull().sum().sort_values(ascending=False)
null_df = null_series.to_frame(name='null_cnt')

col_nm1 = null_df.index[0]
col_nm2 = null_df.index[1]

print(f'1번째 결측가 많은 컬럼(결측치 수) : {null_df.index[0]}({null_df.iloc[0,0]})')
print(f'2번째 결측가 많은 컬럼(결측치 수) : {null_df.index[1]}({null_df.iloc[1,0]})')

1번째 결측가 많은 컬럼(결측치 수) : f1(31)
2번째 결측가 많은 컬럼(결측치 수) : f3(29)

#### 2.첫 번째로 결측치가 많은 컬럼에서 결측치가 있는 데이터(행)를 삭제하시오.

In [51]:
df = df.dropna(subset=[col_nm1])

df.isnull().sum()

id             0
age            0
city           0
f1             0
f2             0
f3            19
f4             0
f5             0
subscribed     0
views          2
dtype: int64

#### 3.두 번째로 결측치가 많은 컬럼을 최빈값으로 대체하시오.

In [53]:
mode_value = df[col_nm2].mode()[0]
df[col_nm2] = df[col_nm2].fillna(mode_value)

df.isnull().sum()

id            0
age           0
city          0
f1            0
f2            0
f3            0
f4            0
f5            0
subscribed    0
views         2
dtype: int64

#### 4.'f3'컬럼의 'gold'값을 가진 데이터의 수를 정수형으로 구하시오.

In [54]:
cond = df['f3'] == 'gold'

print("gold 데이터의 수 :", sum(cond))

gold 데이터의 수 : 63