In [97]:
import pandas as pd
import numpy as np

## Series

In [98]:
menu = pd.Series(["비빔밥", "김치찌개", "된장찌개"])
menu

0     비빔밥
1    김치찌개
2    된장찌개
dtype: object

In [99]:
price = pd.Series([1000,9000,8000])
price

0    1000
1    9000
2    8000
dtype: int64

## DataFrame

In [100]:
df = pd.DataFrame({
    "메뉴" :  menu,
    "가격" :  price
})
df

     메뉴    가격
0   비빔밥  1000
1  김치찌개  9000
2  된장찌개  8000

In [101]:
df = pd.DataFrame({
    "메뉴" : ["비빔밥", "김치찌개", "된장찌개"],
    "가격" : [10000,9000,8000],
    "원산지" : ["국내산", "국내산", "국내산"]
})
df

     메뉴     가격  원산지
0   비빔밥  10000  국내산
1  김치찌개   9000  국내산
2  된장찌개   8000  국내산

#### 컬럼 선택 Series

In [102]:
df["메뉴"]

0     비빔밥
1    김치찌개
2    된장찌개
Name: 메뉴, dtype: object

#### 컬럼 선택 DataFrame

In [103]:
df[["메뉴"]]

     메뉴
0   비빔밥
1  김치찌개
2  된장찌개

In [104]:
df[["메뉴", "가격"]]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

In [105]:
# 이중구조의 []의 가시성을 다중컬럼 사용 시 list변수 사용 추천
cols = ["메뉴", "가격"]
df[cols]

     메뉴     가격
0   비빔밥  10000
1  김치찌개   9000
2  된장찌개   8000

## 데이터 저장 및 불러오기

In [106]:
df = pd.DataFrame({
    "메뉴" : ["아메리카노", "카페라떼", "카페모카", "카푸치노", "에스프레소", "밀크티", "녹차"],
    "가격" : [4500,5000,5500,5000,4000,5900,5300],
    "칼로리" : [10,110,250,110,20,210,0], 
})

df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [107]:
df.to_csv("cafe.csv", index=False)

In [108]:
df = pd.read_csv("cafe.csv")
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

## 탐색적 데이터 분석(EDA)

In [109]:
# 위에서부터 부분조회
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [110]:
#아래에서부터 부분조회
df.tail()

      메뉴    가격  칼로리
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210
6     녹차  5300    0

In [111]:
#랜덤으로 부분조회

In [112]:
df.sample(3)

     메뉴    가격  칼로리
6    녹차  5300    0
5   밀크티  5900  210
2  카페모카  5500  250

In [113]:
#데이터 프레임 크기
df.shape

(7, 3)

In [114]:
#데이터 프레임 구조 분석
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      int64
dtypes: int64(2), object(1)
memory usage: 300.0+ bytes

In [115]:
#데이터 프레임 상관관계분석
df.corr(numeric_only=True)

           가격       칼로리
가격   1.000000  0.713227
칼로리  0.713227  1.000000

## 범주형 데이터 분석

In [116]:
df_car = pd.DataFrame({
    "car" : ["Sedan", "SUV", "Sedan", "SUV", "SUV", "SUV","Sedan","Sedan","Sedan","Sedan","Sedan"],
    "size" : ["S", "M", "S", "S", "M", "M", "L", "S", "S", "M", "S"]
})

df_car.head()

     car size
0  Sedan    S
1    SUV    M
2  Sedan    S
3    SUV    S
4    SUV    M

In [117]:
#고유값 수 확인
df_car.nunique()

car     2
size    3
dtype: int64

In [118]:
#고유값 확인
car_unique = df_car["car"].unique()
size_unique = df_car["size"].unique()
print("car 고유값 종류 : " + str(car_unique))
print("size 고유값 종류 : " + str(size_unique))

car 고유값 종류 : ['Sedan' 'SUV']
size 고유값 종류 : ['S' 'M' 'L']

In [119]:
print(df_car["car"].value_counts())
print(df_car["size"].value_counts())

car
Sedan    7
SUV      4
Name: count, dtype: int64
size
S    6
M    4
L    1
Name: count, dtype: int64

## 기술통계

In [120]:
#수치형 기술통계
df.describe()

                가격         칼로리
count     7.000000    7.000000
mean   5028.571429  101.428571
std     631.702160   99.402980
min    4000.000000    0.000000
25%    4750.000000   15.000000
50%    5000.000000  110.000000
75%    5400.000000  160.000000
max    5900.000000  250.000000

In [121]:
#범주형 기술통계
df_car.describe(include="O")

          car size
count      11   11
unique      2    3
top     Sedan    S
freq        7    6

In [122]:
df.describe(include="O")

           메뉴
count       7
unique      7
top     아메리카노
freq        1

#### 형변환

In [123]:
df = pd.DataFrame({
    "메뉴" : ["아메리카노", "카페라떼", "카페모카", "카푸치노", "에스프레소", "밀크티", "녹차"],
    "가격" : [4500.0,5000.0,5500.0,5000.0,4000.0,5900.0,5300.0],
    "칼로리" : ["10","110","250","110","20","210","0"], 
})

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      float64
 2   칼로리     7 non-null      object
dtypes: float64(1), object(2)
memory usage: 300.0+ bytes

In [124]:
df["가격"] = df["가격"].astype("int")
df["칼로리"] = df["칼로리"].astype("float")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   메뉴      7 non-null      object
 1   가격      7 non-null      int64
 2   칼로리     7 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 300.0+ bytes

## 컬럼추가

In [125]:
df = pd.read_csv("cafe.csv")

df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [126]:
discount = 0.2
df["할인가"] = df["가격"] * (1-discount)
df["할인가"] = df["할인가"].astype("int")

df.head()

      메뉴    가격  칼로리   할인가
0  아메리카노  4500   10  3600
1   카페라떼  5000  110  4000
2   카페모카  5500  250  4400
3   카푸치노  5000  110  4000
4  에스프레소  4000   20  3200

## 행삭제, 열삭제

In [127]:
df.drop(1, axis=0, inplace=True)
df.head()

      메뉴    가격  칼로리   할인가
0  아메리카노  4500   10  3600
2   카페모카  5500  250  4400
3   카푸치노  5000  110  4000
4  에스프레소  4000   20  3200
5    밀크티  5900  210  4720

In [128]:
df = df.drop("할인가", axis=1)
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210

## 인덱싱/슬라이싱

In [129]:
df = pd.read_csv("cafe.csv")
df.head()

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20

In [130]:
# 열 선택
df.loc[0]

메뉴     아메리카노
가격      4500
칼로리       10
Name: 0, dtype: object

In [131]:
#데이터 선택
df.loc[1,"가격"]

np.int64(5000)

In [132]:
#행 정보 슬라이싱
df.loc[0:3,"가격"]

0    4500
1    5000
2    5500
3    5000
Name: 가격, dtype: int64

In [133]:
#컬럼 정보 슬라이싱
df.loc[2,"메뉴" : "가격"]

메뉴    카페모카
가격    5500
Name: 2, dtype: object

In [134]:
#컬럼 정보 슬라이싱
df.loc[2,["가격", "메뉴"]]

가격    5500
메뉴    카페모카
Name: 2, dtype: object

In [135]:
df = pd.read_csv("cafe.csv")
df.drop(0, axis=0, inplace=True)

df.head()

      메뉴    가격  칼로리
1   카페라떼  5000  110
2   카페모카  5500  250
3   카푸치노  5000  110
4  에스프레소  4000   20
5    밀크티  5900  210

In [136]:
df.iloc[0]

메뉴     카페라떼
가격     5000
칼로리     110
Name: 1, dtype: object

In [137]:
df.iloc[0:2,0:2]

     메뉴    가격
1  카페라떼  5000
2  카페모카  5500

## 데이터 추가, 변경

In [138]:
df = pd.read_csv("cafe.csv")
df.head(2)

      메뉴    가격  칼로리
0  아메리카노  4500   10
1   카페라떼  5000  110

In [139]:
#결측치 대입
df["원산지"] = np.nan
df.head(2)

      메뉴    가격  칼로리  원산지
0  아메리카노  4500   10  NaN
1   카페라떼  5000  110  NaN

In [140]:
df.loc[0,"원산지"] = "콜롬비아"
df.loc[2:3,"원산지"] = "과테말라"

df.head(4)

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_16468\806745861.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '콜롬비아' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[0,"원산지"] = "콜롬비아"

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN
2   카페모카  5500  250  과테말라
3   카푸치노  5000  110  과테말라

In [141]:
#행추가(리스트)
df.loc["시즌"] = ["크리스마스라떼", 6000, 300, "한국"]
df.tail(2)

         메뉴    가격  칼로리  원산지
6        녹차  5300    0  NaN
시즌  크리스마스라떼  6000  300   한국

In [142]:
df.loc[7] = {"메뉴":"딴짓라떼", "가격":2000,"칼로리":20}
df.tail(2)

         메뉴    가격  칼로리  원산지
시즌  크리스마스라떼  6000  300   한국
7      딴짓라떼  2000   20  NaN

In [143]:
df.drop("시즌", axis=0, inplace=True)
df.to_csv("cafe2.csv", index=False)

## 정렬

In [144]:
df = pd.read_csv("cafe2.csv")
df.head(2)

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN

In [145]:
#인덱스 기준
df.sort_index(ascending=False, inplace=True) #ascending : True(오름차순), False(내림차순)
df.head(3)

     메뉴    가격  칼로리  원산지
7  딴짓라떼  2000   20  NaN
6    녹차  5300    0  NaN
5   밀크티  5900  210  NaN

In [146]:
# value 기준
df.sort_values("가격", ascending=False, inplace=True)
df.head(3)

     메뉴    가격  칼로리   원산지
5   밀크티  5900  210   NaN
2  카페모카  5500  250  과테말라
6    녹차  5300    0   NaN

In [147]:
#다중 조건
df.sort_values(["가격","메뉴"], ascending=[False,True], inplace=True)
df.head()

     메뉴    가격  칼로리   원산지
5   밀크티  5900  210   NaN
2  카페모카  5500  250  과테말라
6    녹차  5300    0   NaN
1  카페라떼  5000  110   NaN
3  카푸치노  5000  110  과테말라

In [148]:
#인덱스 재설정
df.reset_index(drop=True, inplace=True)

df

      메뉴    가격  칼로리   원산지
0    밀크티  5900  210   NaN
1   카페모카  5500  250  과테말라
2     녹차  5300    0   NaN
3   카페라떼  5000  110   NaN
4   카푸치노  5000  110  과테말라
5  아메리카노  4500   10  콜롬비아
6  에스프레소  4000   20   NaN
7   딴짓라떼  2000   20   NaN

## 필터링

In [149]:
cond = df["칼로리"]>50
df[cond]

     메뉴    가격  칼로리   원산지
0   밀크티  5900  210   NaN
1  카페모카  5500  250  과테말라
3  카페라떼  5000  110   NaN
4  카푸치노  5000  110  과테말라

In [150]:
#not 연산
df[~cond]

      메뉴    가격  칼로리   원산지
2     녹차  5300    0   NaN
5  아메리카노  4500   10  콜롬비아
6  에스프레소  4000   20   NaN
7   딴짓라떼  2000   20   NaN

In [151]:
#주어진 값이 있는지로 조회
menus = ["녹차", "카푸치노","카페라떼"]
cond = df["메뉴"].isin(menus)

df[cond]

     메뉴    가격  칼로리   원산지
2    녹차  5300    0   NaN
3  카페라떼  5000  110   NaN
4  카푸치노  5000  110  과테말라

## 결측치 탐색

In [152]:
df = pd.read_csv("cafe2.csv")
df.head(2)

      메뉴    가격  칼로리   원산지
0  아메리카노  4500   10  콜롬비아
1   카페라떼  5000  110   NaN

In [153]:
#전체 결측치 확인
df.isnull()

      메뉴     가격    칼로리    원산지
0  False  False  False  False
1  False  False  False   True
2  False  False  False  False
3  False  False  False  False
4  False  False  False   True
5  False  False  False   True
6  False  False  False   True
7  False  False  False   True

In [154]:
#컬럼별 결측치 갯수 확인
df.isnull().sum()

메뉴     0
가격     0
칼로리    0
원산지    5
dtype: int64

In [155]:
#결측치 채우기(fin)

df["원산지"] = df["원산지"].fillna("코스타리카")
df

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓라떼  2000   20  코스타리카

In [156]:
df.to_csv('cafe3.csv',index=False)

In [157]:
#repalce() vs str.replace()
df = df.replace('아메리카노', '룽고')
df

      메뉴    가격  칼로리    원산지
0     룽고  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6     녹차  5300    0  코스타리카
7   딴짓라떼  2000   20  코스타리카

In [158]:
df['메뉴'] = df['메뉴'].str.replace('녹차', '그린티')
df

      메뉴    가격  칼로리    원산지
0     룽고  4500   10   콜롬비아
1   카페라떼  5000  110  코스타리카
2   카페모카  5500  250   과테말라
3   카푸치노  5000  110   과테말라
4  에스프레소  4000   20  코스타리카
5    밀크티  5900  210  코스타리카
6    그린티  5300    0  코스타리카
7   딴짓라떼  2000   20  코스타리카

In [166]:
df = pd.read_csv('cafe3.csv')
df.loc[[0,6]]

      메뉴    가격  칼로리    원산지
0  아메리카노  4500   10   콜롬비아
6     녹차  5300    0  코스타리카

In [165]:
change = {'아메리카노':'롱고', '녹차': '그린티'}
df = df.replace(change)
df.loc[[0,6]]

    메뉴    가격  칼로리    원산지
0   롱고  4500   10   콜롬비아
6  그린티  5300    0  코스타리카

In [168]:
df.loc[6, '원산지'] = '대한민국'
df.loc[[6]]

   메뉴    가격  칼로리   원산지
6  녹차  5300    0  대한민국

In [170]:
#신규 컬럼 추가 및 초기값 설정
df.loc[1:2, '이벤트가'] = 1000
df.head(3)

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0
2   카페모카  5500  250   과테말라  1000.0

In [172]:
df.to_csv('cafe4.csv', index=False)