In [1]:
import numpy as np
import pandas as pd

## S1.필터링,최솟값,중앙값

In [3]:
df = pd.read_csv('type1_data1.csv')
df

        id   age city    f1  f2      f3    f4         f5  subscribed   views
0     id01   2.0   서울   NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1     id02   9.0   서울  70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
2     id03  27.0   서울  61.0   1    gold  ISTJ  17.252986  2024-03-16  7312.0
3     id04  75.0   서울   NaN   2     NaN  INFP  52.667078  2024-07-21   493.0
4     id05  24.0   서울  85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
..     ...   ...  ...   ...  ..     ...   ...        ...         ...     ...
115  id114  22.0   대구  23.0   0    gold  INTP   0.000000  2025-02-17  9747.0
116  id115  23.0   부산  65.0   0     vip  ENTP   0.000000  2025-02-17  5628.0
117  id116  23.0   서울  12.0   1  silver  INFP   0.000000  2025-02-17  1267.0
118  id117  23.0   대구  65.0   2    gold  INFP   0.000000  2025-02-17  6543.0
119  id118  24.0   부산  94.0   1     vip  ESFJ   0.000000  2025-02-17  2356.0

[120 rows x 10 columns]

#### 1.'f5'컬럼이 0이 아닌 데이터(행)을 구하시오.

In [5]:
cond = df['f5'] != 0
df = df[cond]
df

        id    age city    f1  f2    f3    f4         f5  subscribed    views
0     id01    2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16   6820.0
1     id02    9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12   2534.0
2     id03   27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16   7312.0
3     id04   75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21    493.0
4     id05   24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07   1338.0
..     ...    ...  ...   ...  ..   ...   ...        ...         ...      ...
97    id97  100.0   경기   NaN   0  gold  INFP  67.886373  2024-03-18   6687.0
98    id98   39.0   경기  58.0   2   NaN  INFP  98.429899  2024-10-02    865.0
99    id99    1.0   경기  47.0   0  gold  ESFJ  97.381034  2024-12-02   6090.0
100  id100   47.0   경기  53.0   0   vip  ESFP  33.308999  2024-02-21  15535.0
101   id68   35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29   8599.0

[102 rows x 10 columns]

#### 2.앞에서 구한 데이터에 'views' 컬럼 결측치를 'views' 컬럼의 최솟값으로 채워주세요.

In [14]:
print("결측치 수 :", df['views'].isnull().sum())

min_value = df['views'].min()
df['views'] = df['views'].fillna(min_value)

df

결측치 수 : 4

C:\Users\Public\Documents\ESTsoft\CreatorTemp\ipykernel_7000\911338026.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['views'] = df['views'].fillna(min_value)

        id    age city    f1  f2    f3    f4         f5  subscribed    views
0     id01    2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16   6820.0
1     id02    9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12   2534.0
2     id03   27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16   7312.0
3     id04   75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21    493.0
4     id05   24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07   1338.0
..     ...    ...  ...   ...  ..   ...   ...        ...         ...      ...
97    id97  100.0   경기   NaN   0  gold  INFP  67.886373  2024-03-18   6687.0
98    id98   39.0   경기  58.0   2   NaN  INFP  98.429899  2024-10-02    865.0
99    id99    1.0   경기  47.0   0  gold  ESFJ  97.381034  2024-12-02   6090.0
100  id100   47.0   경기  53.0   0   vip  ESFP  33.308999  2024-02-21  15535.0
101   id68   35.0   경기  45.0   2  gold  ISFP  67.886373  2024-07-29   8599.0

[102 rows x 10 columns]

#### 3.'views' 컬럼의 중앙값을 계산해 정수로 구하시오.

In [16]:
median_value = df['views'].median()

print(int(median_value))

5924

## S2.카테고리, 인덱스, 문자열 슬라이싱

In [17]:
df = pd.read_csv('type1_data1.csv')

#### 1.'subscribed'컬럼에서 가장 빈도수가 많은 날짜를 구하시오.

In [23]:
mode_value = df['subscribed'].mode()
print(mode_value[0])

2025-02-17

#### 2.앞에서 구한 날짜의 일(day)값을 정수로 구하시오.

In [31]:
date = str(mode_value[0])
print(date[-2:])

17

## S3.파생변수, 정렬, 인덱스

In [47]:
df = pd.read_csv('type1_data1.csv')
len(df)

120

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          120 non-null    object
 1   age         120 non-null    float64
 2   city        120 non-null    object
 3   f1          89 non-null     float64
 4   f2          120 non-null    int64
 5   f3          91 non-null     object
 6   f4          120 non-null    object
 7   f5          120 non-null    float64
 8   subscribed  120 non-null    object
 9   views       116 non-null    float64
dtypes: float64(4), int64(1), object(5)
memory usage: 9.5+ KB

#### 1.결측치가 있는 데이터(행)를 제거하시오.

In [49]:
df = df.dropna()
len(df)

70

#### 2.'views'컬럼을 'f1'컬럼으로 나눈 값을 새로운 컬럼으로 추가하시오.

In [50]:
df['new'] = df['views']/df['f1']
df.head()

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
2,id03,27.0,서울,61.0,1,gold,ISTJ,17.252986,2024-03-16,7312.0,119.868852
5,id06,22.0,서울,57.0,0,vip,INTP,20.129444,2024-09-12,21550.0,378.070175
7,id08,38.0,서울,101.0,1,silver,INFJ,83.685380,2024-03-06,3260.0,32.277228
9,id10,95.0,서울,74.0,1,gold,ISFP,98.429899,2024-04-03,9992.0,135.027027
10,id100,47.0,경기,53.0,0,vip,ESFP,33.308999,2024-02-21,15535.0,293.113208

#### 3.새로운 컬럼 값 중 가장 큰 값을 가진 행의 age를  정수로 구하시오.

In [51]:
df = df.sort_values('new', ascending=False)
df.head()

,id,age,city,f1,f2,f3,f4,f5,subscribed,views,new
115,id114,22.0,대구,23.0,0,gold,INTP,0.000000,2025-02-17,9747.0,423.782609
83,id83,73.0,경기,50.0,1,vip,ENTP,80.138280,2024-09-26,19139.0,382.780000
5,id06,22.0,서울,57.0,0,vip,INTP,20.129444,2024-09-12,21550.0,378.070175
105,id104,21.0,서울,13.0,0,silver,ESFJ,0.000000,2025-02-17,4556.0,350.461538
106,id105,21.0,경기,24.0,0,gold,ESFJ,0.000000,2025-02-17,7654.0,318.916667

In [56]:
target_age = df.iloc[0,1]
print(int(target_age))

22

## S4.값변경, 정렬, 합계

In [61]:
df = pd.read_csv('type1_data1.csv')

#### 1.'views'컬럼의 결측 데이터를 0으로 대체하시오.|

In [74]:
cond = df['views'].isnull()

#views가 결측치인 행 확인
idxs =df[cond].index
df.loc[idxs]

      id   age city    f1  f2   f3    f4         f5  subscribed  views
20  id20  11.0   서울  51.0   1  NaN  INTJ  91.297791  2024-07-16    NaN
39  id39  56.0   부산  50.0   0  NaN  INFJ  33.308999  2024-12-22    NaN
48  id48  18.0   대구   NaN   0  NaN  ENFP  20.129444  2024-03-25    NaN
82  id82  48.0   경기   NaN   0  NaN  ENTJ  37.113739  2024-10-17    NaN

In [75]:
df['views'] = df['views'].fillna(0)
df.loc[idxs]

      id   age city    f1  f2   f3    f4         f5  subscribed  views
20  id20  11.0   서울  51.0   1  NaN  INTJ  91.297791  2024-07-16    0.0
39  id39  56.0   부산  50.0   0  NaN  INFJ  33.308999  2024-12-22    0.0
48  id48  18.0   대구   NaN   0  NaN  ENFP  20.129444  2024-03-25    0.0
82  id82  48.0   경기   NaN   0  NaN  ENTJ  37.113739  2024-10-17    0.0

#### 2.'views'컬럼에서 상위 10번째 값을 구하시오.

In [79]:
df = df.sort_values('views', ascending=False)
df.iloc[9:10]

        id   age city    f1  f2   f3    f4   f5  subscribed   views
113  id112  22.0   서울  45.0   2  vip  ENTP  0.0  2025-02-17  9877.0

#### 3.'views'컬럼에서 상위 10개의 값을 상위 10번째 값으로 대체하시오.

In [90]:
value = df.iloc[9, -1]
df.iloc[:10,-1] = value
df.head(10)

        id   age city    f1  f2      f3    f4         f5  subscribed   views
5     id06  22.0   서울  57.0   0     vip  INTP  20.129444  2024-09-12  9877.0
56    id56  59.0   대구   NaN   1     vip  ESTJ  73.586397  2024-04-05  9877.0
83    id83  73.0   경기  50.0   1     vip  ENTP  80.138280  2024-09-26  9877.0
32    id32  25.0   부산  64.0   0     vip  ISFJ  13.049921  2024-05-24  9877.0
100  id100  47.0   경기  53.0   0     vip  ESFP  33.308999  2024-02-21  9877.0
10   id100  47.0   경기  53.0   0     vip  ESFP  33.308999  2024-02-21  9877.0
104  id103  21.0   부산  53.0   0     vip  ISFP   0.000000  2025-02-17  9877.0
114  id113  22.0   경기  34.0   2  silver  ENTP   0.000000  2025-02-17  9877.0
9     id10  95.0   서울  74.0   1    gold  ISFP  98.429899  2024-04-03  9877.0
113  id112  22.0   서울  45.0   2     vip  ENTP   0.000000  2025-02-17  9877.0

#### 4.'views'컬럼의 전체 합을 정수로 구하시오.

In [91]:
sum_value = df['views'].sum()
print("views 전체 합 :", int(sum_value))

views 전체 합 : 652812

## S5.문자열 슬라이싱, 파생변수, 평균값

In [101]:
df = pd.read_csv('type1_data1.csv')
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.'f4'컬럼 데이터에 'FJ'가 포함된 데이터를 찾으시오.

In [102]:
cond = df['f4'].str.contains('FJ')
df = df[cond]
df.head()

     id   age city     f1  f2      f3    f4         f5  subscribed   views
0  id01   2.0   서울    NaN   0    gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울   70.0   1     NaN  ENFJ  60.339826  2024-05-12  2534.0
4  id05  24.0   서울   85.0   2     NaN  ISFJ  29.269869  2024-03-07  1338.0
6  id07  36.3   서울   60.0   1     NaN  ISFJ   9.796378  2024-01-11    61.0
7  id08  38.0   서울  101.0   1  silver  INFJ  83.685380  2024-03-06  3260.0

#### 2.찾은 데이터 중에서 'f2'컬럼의 평균값을 구하시오.(반올림 후 소수 둘째 자리까지 계산)

In [108]:
mean_value = df['f2'].mean()
mean_value = round(mean_value,2)
print("f2의 평균값 :",mean_value)

f2의 평균값 : 0.61

## S6.필터링, 분산

In [109]:
df = pd.read_csv('type1_data1.csv')
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.'f3'컬럼이 gold이면서 'f2'컬럼이 2인 데이터를 찾으시오.

In [117]:
cond = (df['f3'] == 'gold') & (df['f2'] == 2)
df =df[cond]

df.head()

      id   age city    f1  f2    f3    f4         f5  subscribed   views
18  id18  41.0   서울  87.0   2  gold  ISFJ  80.138280  2024-03-03  7933.0
29  id29 -13.5   부산  47.0   2  gold  ENTP  67.886373  2024-08-28  6793.0
42  id42  65.0   대구  48.0   2  gold  ESTP  33.308999  2024-02-09  5999.0
55  id55  75.0   대구  63.0   2  gold  ENTP  13.049921  2024-02-06  6042.0
64  id64  43.0   경기  62.0   2  gold  ESFP  73.586397  2024-02-22  5995.0

#### 2.찾은 데이터에서 'f1'컬럼의 분산을 구하시오.(반올림 후 소수 둘째 자리까지 계산)

In [119]:
var_value = df['f1'].var()
var_value = round(var_value,2)
print("f1의 분산 :", var_value)

f1의 분산 : 235.43

## S7.값 변경(연산), 필터링 절댓값

In [120]:
df = pd.read_csv('type1_data1.csv')
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.모든 나이(age)에 1을 더하시오.

In [124]:
df['age'] =df['age']+1
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   3.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02  10.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  28.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  76.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  25.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 2.20대의 'views' 평균과 30대의 'views' 평균의 차이의 절대값을 구하시오.(반올림 후 소수 둘째 자리까지 계산)

In [129]:
cond1 = df['age'].between(20,29)
cond2 = df['age'].between(30,39)

mean20 = df[cond1]['views'].mean()
mean30 = df[cond2]['views'].mean()

abs_diff = abs(mean20-mean30)
abs_diff = round(abs_diff,2)
print(abs_diff)

263.13

## S8.시계열데이터, 필터링, 데이터 개수

In [136]:
df = pd.read_csv('type1_data1.csv')
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.'subscribed' 컬럼이 2024년 2월인 데이터를 찾으시오.

In [137]:
df['subscribed'] = pd.to_datetime(df['subscribed'], format='%Y-%m-%d')
df.head()

     id   age city    f1  f2    f3    f4         f5 subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791 2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826 2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986 2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078 2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869 2024-03-07  1338.0

#### 2.위에서 찾은 데이터 중 'f3' 컬럼이 gold인 데이터의 개수를 구하시오.

In [142]:
cond1 = df['subscribed'].dt.strftime('%Y-%m') == '2024-02'
cond2 = df['f3'] == 'gold'

target_cnt = len(df[cond1&cond2])
print("대상 개수 :", target_cnt)

대상 개수 : 5

## S9.필터링, 카테고리, 최빈값

In [143]:
df = pd.read_csv('type1_data1.csv')
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.'views'컬럼 값이 1000 이하인 데이터(결측값 제외)를 찾으시오.

In [145]:
cond = df['views'] <= 1000
df =df[cond]

#### 2.앞에서 구한 데이터 중 'f4'컬럼의 최빈값을 구하시오.

In [147]:
mode_value = df['f4'].mode()
print('f4 최빈값 :', mode_value[0])

f4 최빈값 : ISFJ

## S10.그룹핑, 최댓값, 정렬

In [148]:
df = pd.read_csv('type1_data1.csv')
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.결측치가 있는 행을 삭제하시오.

In [149]:
df = df.dropna()
df.head()

       id   age city     f1  f2      f3    f4         f5  subscribed    views
2    id03  27.0   서울   61.0   1    gold  ISTJ  17.252986  2024-03-16   7312.0
5    id06  22.0   서울   57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
7    id08  38.0   서울  101.0   1  silver  INFJ  83.685380  2024-03-06   3260.0
9    id10  95.0   서울   74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
10  id100  47.0   경기   53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0

#### 2.결측치가 삭제된 데이터를 사용하여 지역별(city) 평균을 구하시오.

In [151]:
mean_df = df.groupby(['city']).mean(numeric_only=True)
mean_df

            age         f1        f2         f5        views
city
경기    48.704000  61.360000  0.760000  52.106731  8127.880000
대구    49.773333  66.200000  0.666667  27.370166  6819.133333
부산    35.075000  65.875000  0.687500  38.638715  6945.437500
서울    38.000000  60.142857  0.785714  41.122705  7369.142857

#### 3.앞에서 계산한 지역별 평균 데이터에서 'f2'컬럼 값이 가장 큰 지역을 구하시오.

In [158]:
mean_df = mean_df.sort_values('city', ascending=False)
print('f2 컬럼이 가장 큰 지역 :', mean_df.index[0])
print('f2 컬럼이 가장 큰 지역 :', mean_df['f2'].idxmax())

f2 컬럼이 가장 큰 지역 : 서울
f2 컬럼이 가장 큰 지역 : 서울