In [1]:
import pandas as pd
import numpy as numpy

In [2]:
df = pd.DataFrame({
    "A" : ["데이터 분석", "기본 학습서", "퇴근 후 열공"],
    "B" : [10,20,30],
    "C" : ["ab cd", "AB CD", "ab cd"]
})

df

         A   B      C
0   데이터 분석  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [3]:
#문자열 변경 -  replace로만은 전체문자열 중 일부 변경은 불가
df["A"] = df["A"].replace("분석", "시각화")
df

         A   B      C
0   데이터 분석  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [4]:
df["A"] = df["A"].str.replace("분석", "시각화")
df

         A   B      C
0  데이터 시각화  10  ab cd
1   기본 학습서  20  AB CD
2  퇴근 후 열공  30  ab cd

In [5]:
#수치형 변경
df['B'] = df['B'].replace(10,100)
df

         A    B      C
0  데이터 시각화  100  ab cd
1   기본 학습서   20  AB CD
2  퇴근 후 열공   30  ab cd

In [6]:
#str.split()[0] vs str.split().str[0]
df['A'].str.split()[0]

['데이터', '시각화']

In [7]:
df['D'] = df['A'].str.split().str[0]
df

         A    B      C    D
0  데이터 시각화  100  ab cd  데이터
1   기본 학습서   20  AB CD   기본
2  퇴근 후 열공   30  ab cd   퇴근

In [8]:
#특정 문자열 탐색
df['A'].str.contains('기본')

0    False
1     True
2    False
Name: A, dtype: bool

In [12]:
df['기본포함여부'] = df['A'].str.contains('기본')
df

         A    B      C    D  기본포함여부
0  데이터 시각화  100  ab cd  데이터   False
1   기본 학습서   20  AB CD   기본    True
2  퇴근 후 열공   30  ab cd   퇴근   False

In [13]:
df['문자길이'] = df['A'].str.len()
df

         A    B      C    D  기본포함여부  문자길이
0  데이터 시각화  100  ab cd  데이터   False     7
1   기본 학습서   20  AB CD   기본    True     6
2  퇴근 후 열공   30  ab cd   퇴근   False     7

In [14]:
#소문자 변환
df['C'] = df['C'].str.lower()
df['C']

0    ab cd
1    ab cd
2    ab cd
Name: C, dtype: object

In [15]:
df['C'] = df['C'].str.upper()
df['C']

0    AB CD
1    AB CD
2    AB CD
Name: C, dtype: object

In [17]:
#형변환 + 문자변환
df['C'] = df['C'].str.lower()
df['C'] = df['C'].str.replace(' ', '')
df[['C']]

      C
0  abcd
1  abcd
2  abcd

## 내장함수

In [55]:
df = pd.read_csv('cafe4.csv')
df

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  4500   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0
2   카페모카  5500  250   과테말라  1000.0
3   카푸치노  5000  110   과테말라     NaN
4  에스프레소  4000   20  코스타리카     NaN
5    밀크티  5900  210  코스타리카     NaN
6     녹차  5300    0   대한민국     NaN
7   딴짓라떼  2000   20  코스타리카     NaN

In [56]:
#len()
print("행 수 : ", str(len(df)))
print("행 수 : ", str(df.shape[0]))
print("열 수 : ", str(df.shape[1]))

행 수 :  8
행 수 :  8
열 수 :  5

In [57]:
#조건에 맞는 행 수
cond = df['가격'] > 5000

#sum()으로 행 수
print("sum  : ", sum(cond))
#len()으로 행 수 
print("len : ", len(df[cond]))

sum  :  3
len :  3

In [58]:
#데이터플레임의 sum(numeric_only=True) : 수치형 컬럼의 총합 반환
df.sum(numeric_only = True)

가격      37200.0
칼로리       730.0
이벤트가     2000.0
dtype: float64

#### 행과 열 변경

In [59]:
df.T

          0       1       2     3      4      5     6      7
메뉴    아메리카노    카페라떼    카페모카  카푸치노  에스프레소    밀크티    녹차   딴짓라떼
가격     4500    5000    5500  5000   4000   5900  5300   2000
칼로리      10     110     250   110     20    210     0     20
원산지    콜롬비아   코스타리카    과테말라  과테말라  코스타리카  코스타리카  대한민국  코스타리카
이벤트가    NaN  1000.0  1000.0   NaN    NaN    NaN   NaN    NaN

In [60]:
#열 방향으로 sum
df.sum(axis=1, numeric_only=True) #수치형 컬럼인 가격+칼로리값 반환

0    4510.0
1    6110.0
2    6750.0
3    5110.0
4    4020.0
5    6110.0
6    5300.0
7    2020.0
dtype: float64

In [61]:
df.describe()

                가격         칼로리    이벤트가
count     8.000000    8.000000     2.0
mean   4650.000000   91.250000  1000.0
std    1220.070256   96.427249     0.0
min    2000.000000    0.000000  1000.0
25%    4375.000000   17.500000  1000.0
50%    5000.000000   65.000000  1000.0
75%    5350.000000  135.000000  1000.0
max    5900.000000  250.000000  1000.0

In [62]:
#기초 통계값
print("최댓값 :", df['가격'].max())
print("최솟값 :", df['가격'].min())
print("평균값 :", df['가격'].mean())
print("중앙값 :", df['가격'].median())
print("합계 :", df['가격'].sum())
print("표준편차 :", df['가격'].std())
print("분산 :", df['가격'].var())

최댓값 : 5900
최솟값 : 2000
평균값 : 4650.0
중앙값 : 5000.0
합계 : 37200
표준편차 : 1220.070255588353
분산 : 1488571.4285714286

In [37]:
#quantile (4분위수)

5900

In [39]:
print('1분위수(25%) :',df['가격'].quantile(0.25))
print('중앙값(50%) :',df['가격'].quantile(0.5))
print('3분위수(75%) :',df['가격'].quantile(0.75))

1분위수(25%) : 4375.0
중앙값(50%) : 5000.0
3분위수(75%) : 5350.0

In [40]:
#1분위보다 낮은 값 찾기
cond = df['가격'].quantile(0.25) > df['가격']
df[cond]

      메뉴    가격  칼로리    원산지  이벤트가
4  에스프레소  4000   20  코스타리카   NaN
7   딴짓라떼  2000   20  코스타리카   NaN

In [42]:
#3분위보다 큰 값 찾기
cond = df['가격'].quantile(0.75) < df['가격']
df[cond]

     메뉴    가격  칼로리    원산지    이벤트가
2  카페모카  5500  250   과테말라  1000.0
5   밀크티  5900  210  코스타리카     NaN

In [46]:
df['원산지'].value_counts()

원산지
코스타리카    4
과테말라     2
콜롬비아     1
대한민국     1
Name: count, dtype: int64

In [44]:
#최빈값 찾기
df['원산지'].mode()[0] #최빈값은 1개가 아닐 수 있어서 mode()의 결과는 series이다.

'코스타리카'

In [49]:
df.loc[0,"가격"] = 5900
df

      메뉴    가격  칼로리    원산지    이벤트가
0  아메리카노  5900   10   콜롬비아     NaN
1   카페라떼  5000  110  코스타리카  1000.0
2   카페모카  5500  250   과테말라  1000.0
3   카푸치노  5000  110   과테말라     NaN
4  에스프레소  4000   20  코스타리카     NaN
5    밀크티  5900  210  코스타리카     NaN
6     녹차  5300    0   대한민국     NaN
7   딴짓라떼  2000   20  코스타리카     NaN

In [50]:
#가격이 가장 비싼 메뉴 찾기
max_idx = df['가격'].idxmax() #idxmax()는 max값이 복수여도 1개만 반환
df.loc[max_idx]

메뉴      아메리카노
가격       5900
칼로리        10
원산지      콜롬비아
이벤트가      NaN
Name: 0, dtype: object

In [51]:
cond = df['가격'].max() == df['가격']
df[cond]

      메뉴    가격  칼로리    원산지  이벤트가
0  아메리카노  5900   10   콜롬비아   NaN
5    밀크티  5900  210  코스타리카   NaN

In [52]:
#가격이 가장 싼 메뉴 찾기
min_idx = df['가격'].idxmin()
df.loc[min_idx]

메뉴       딴짓라떼
가격       2000
칼로리        20
원산지     코스타리카
이벤트가      NaN
Name: 7, dtype: object

In [53]:
cond = df['가격'].min() == df['가격']
df[cond]

     메뉴    가격  칼로리    원산지  이벤트가
7  딴짓라떼  2000   20  코스타리카   NaN