In [1]:
import numpy as np
import pandas as pd

## S11.슬라이싱, 사분위수, 결측치 제거

In [7]:
df = pd.read_csv('type1_data1.csv')
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.데이터에서 결측치가 있는 데이터(행)을 모두 제거하시오.

In [8]:
df = df.dropna()
print("행 수 :", len(df))

행 수 : 70

#### 2.결측치가 제거된 데이터를 사용하여 앞에서부터 70% 데이터를 구하시오.
#### (단, 데이터 70 % 지점의 index가 소수점으로 계산될 경우 소수점 이하는 버림)

In [9]:
end = int(len(df) * 0.7)
df = df.iloc[:end]

print("행 수 :", len(df))
df.head()

행 수 : 49

       id   age city     f1  f2      f3    f4         f5  subscribed    views
2    id03  27.0   서울   61.0   1    gold  ISTJ  17.252986  2024-03-16   7312.0
5    id06  22.0   서울   57.0   0     vip  INTP  20.129444  2024-09-12  21550.0
7    id08  38.0   서울  101.0   1  silver  INFJ  83.685380  2024-03-06   3260.0
9    id10  95.0   서울   74.0   1    gold  ISFP  98.429899  2024-04-03   9992.0
10  id100  47.0   경기   53.0   0     vip  ESFP  33.308999  2024-02-21  15535.0

#### 앞에서 구한 70% 데이터 중 'views' 컬럼의 3사분위수에서 1사분위수를 뺀 값을 소수점 이하를 버리고 정수부분만 구하시오.

In [10]:
q3 = df['views'].quantile(0.75)
q1 = df['views'].quantile(0.25)

iqr = int(q3-q1)
print("IQR :", iqr)

IQR : 2771

## S12.결측치 처리, 최빈값 데이터 개수

In [49]:
df = pd.read_csv('type1_data1.csv')
print("행 수 :", len(df))
df.head()

행 수 : 120

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.결측치가 가장 많은 두 컬럼을 찾으시오.

In [50]:
null_series = df.isnull().sum().sort_values(ascending=False)
null_df = null_series.to_frame(name='null_cnt')

col_nm1 = null_df.index[0]
col_nm2 = null_df.index[1]

print(f'1번째 결측가 많은 컬럼(결측치 수) : {null_df.index[0]}({null_df.iloc[0,0]})')
print(f'2번째 결측가 많은 컬럼(결측치 수) : {null_df.index[1]}({null_df.iloc[1,0]})')

1번째 결측가 많은 컬럼(결측치 수) : f1(31)
2번째 결측가 많은 컬럼(결측치 수) : f3(29)

#### 2.첫 번째로 결측치가 많은 컬럼에서 결측치가 있는 데이터(행)를 삭제하시오.

In [51]:
df = df.dropna(subset=[col_nm1])

df.isnull().sum()

id             0
age            0
city           0
f1             0
f2             0
f3            19
f4             0
f5             0
subscribed     0
views          2
dtype: int64

#### 3.두 번째로 결측치가 많은 컬럼을 최빈값으로 대체하시오.

In [53]:
mode_value = df[col_nm2].mode()[0]
df[col_nm2] = df[col_nm2].fillna(mode_value)

df.isnull().sum()

id            0
age           0
city          0
f1            0
f2            0
f3            0
f4            0
f5            0
subscribed    0
views         2
dtype: int64

#### 4.'f3'컬럼의 'gold'값을 가진 데이터의 수를 정수형으로 구하시오.

In [54]:
cond = df['f3'] == 'gold'

print("gold 데이터의 수 :", sum(cond))

gold 데이터의 수 : 63

## S13.결측 데이터 찾기, 필터링, 평균값

In [55]:
df = pd.read_csv('type1_data1.csv')
print("행 수 :", len(df))
df.head()

행 수 : 120

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.'f1'컬럼에 결측치가 있는 데이터만 선택하시오.

In [56]:
cond = df['f1'].isnull()
df = df[cond]
print("행 수 :", len(df))
df.head()

행 수 : 31

      id   age city  f1  f2    f3    f4         f5  subscribed   views
0   id01   2.0   서울 NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
3   id04  75.0   서울 NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
12  id12  20.0   서울 NaN   0   NaN  ESTP  91.297791  2024-11-30  1367.0
17  id17  74.0   서울 NaN   1  gold  ISTP  67.886373  2024-10-26  9441.0
19  id19  53.0   서울 NaN   0  gold  ISFP  83.685380  2024-12-24  5287.0

#### 2.선택된 데이터에서 'age'컬럼의 평균값을 구하시오.
#### (반올림 후 소수 첫째 자리까지 계산)

In [57]:
mean_value = df['age'].mean()
print("age 평균값 :", round(mean_value, 1))

age 평균값 : 53.6

## S14.중복 데이터 제거, 값 변경, 데이터 개수

In [64]:
df = pd.read_csv('type1_data1.csv')
print("행 수 :", len(df))
df.head()

행 수 : 120

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.중복 데이터를 제거하시오.

In [65]:
df= df.drop_duplicates()
print("행 수 :", len(df))

행 수 : 118

#### 2.'f3'컬럼의 결측치를 0, 'silver'는 1, 'gold'는 2, 'vip'는 3으로 변환하시오.

In [66]:
mapping = {'silver' : 1, 'gold' : 2, 'vip' : 3}

df['f3'] = df['f3'].fillna(0)
df['f3'] = df['f3'].map(mapping)

df.head()

     id   age city    f1  f2   f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  2.0  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1  NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  2.0  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2  NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2  NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 3.변환된 'f3'컬럼의 총합을 정수형으로 구하시오.

In [68]:
sum_value = int(df['f3'].sum())
print('f3의 총합 :', sum_value)

f3의 총합 : 167

## S15.컬럼 삭제, 행 단위 합계, 필터링

In [69]:
df = pd.read_csv('type1_data1.csv')
print("행 수 :", len(df))
df.head()

행 수 : 120

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.주어진 데이터에서 문자 자료형 컬럼을 삭제하시오.

In [73]:
cols = df.select_dtypes(exclude='object').columns
df = df[cols]

df.head()

    age    f1  f2         f5   views
0   2.0   NaN   0  91.297791  6820.0
1   9.0  70.0   1  60.339826  2534.0
2  27.0  61.0   1  17.252986  7312.0
3  75.0   NaN   2  52.667078   493.0
4  24.0  85.0   2  29.269869  1338.0

#### 2.숫자 자료형 컬럼의 결측치를 0으로 대체하시오.

In [74]:
df = df.fillna(0)
df.head()

    age    f1  f2         f5   views
0   2.0   0.0   0  91.297791  6820.0
1   9.0  70.0   1  60.339826  2534.0
2  27.0  61.0   1  17.252986  7312.0
3  75.0   0.0   2  52.667078   493.0
4  24.0  85.0   2  29.269869  1338.0

#### 3.각 행의 합이 3000보다 큰 값의 개수를 정수로 구하시오.
#### (각 행의 합: 'age'+ 'f1' + 'f2' + 'f5' + 'views')

In [77]:
df['sum'] = df.sum(axis=1)

cond = df['sum'] > 3000

print("3000 초과의 행 수 :", sum(cond))

3000 초과의 행 수 : 88

## S16.이상치, IQR

In [78]:
df = pd.read_csv('type1_data1.csv')
print("행 수 :", len(df))
df.head()

행 수 : 120

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.'views'컬럼의 1사분위수, 3사분위수 그리고 IQR을 계산하시오.

In [79]:
q1 = df['views'].quantile(0.25)
q3 = df['views'].quantile(0.75)
iqr = q3 - q1

print("Q1 :", q1)
print("Q3 :", q3)
print("IQR : ", iqr)

Q1 : 3031.0
Q3 : 8473.5
IQR :  5442.5

#### 2.이상치 조건에 맞는 데이터를 찾으시오.
#### 이상치는 1사분위수 - (IQR * 1.5)보다 작은 값, 3사분위수 + (IQR * 1.5)보다 큰 값

In [80]:
cond1 = df['views'] < q1 - (iqr * 1.5)
cond2 = df['views'] > q3 + (iqr * 1.5)
df = df[cond1 | cond2]

print("행 수 :", len(df))
df.head()

행 수 : 4

      id   age city    f1  f2   f3    f4         f5  subscribed    views
5   id06  22.0   서울  57.0   0  vip  INTP  20.129444  2024-09-12  21550.0
32  id32  25.0   부산  64.0   0  vip  ISFJ  13.049921  2024-05-24  17421.0
56  id56  59.0   대구   NaN   1  vip  ESTJ  73.586397  2024-04-05  19589.0
83  id83  73.0   경기  50.0   1  vip  ENTP  80.138280  2024-09-26  19139.0

#### 3.이상치 데이터의 'views' 컬럼의 합을 정수로 구하시오.

In [82]:
sum_value = int(df['views'].sum())
print("이상치의 합 :", sum_value)

이상치의 합 : 77699

## S17. 이상치, 소수점 있는 데이터 찾기, 표준편차

In [101]:
df = pd.read_csv('type1_data1.csv')
print("행 수 :", len(df))
df.head()

행 수 : 120

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.'views' 컬럼의 표준편차를 구하시오.

In [102]:
std_value1 = df['views'].std()
print("표준편차 :", std_value)

표준편차 : 1697.0889536693905

#### 2.'age'컬럼의 이상치(소수점 나이, 음수 나이, 0살)을 제거하고 'views' 컬럼의 표준편차를 구하시오.

In [103]:
cond = df['age'] <= 0
df = df[~cond]

cond = df['age'] == round(df['age'],0)
df = df[cond]

#### 3.이상치 제거 전후의 'view'컬럼의 표준편차를 더하여, 반 올림 후 소수 둘째 자리까지 구하시오.

In [104]:
std_value2 = df['views'].std()
sum_value = std_value1 + std_value2

print("표준편차의 합 :", round(sum_value, 2))

표준편차의 합 : 8297.31

## S18.데이터(행) 기준 평균값, 인덱싱

In [110]:
df = pd.read_csv('type1_data2.csv', index_col='year')
print("행 수 :", len(df))
df.head()

행 수 : 5

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
year,,,,,,,,,,,,,,,,,,,,,
2000,137,74,114,140,80,150,16,133,178,181,...,124,94,118,12,50,191,137,174,56,128
2001,176,87,64,110,128,16,8,4,123,87,...,59,22,3,108,17,104,101,161,156,43
2002,128,132,123,112,134,160,180,47,115,155,...,160,111,116,75,48,51,81,101,194,73
2003,78,45,26,50,177,119,47,72,163,125,...,163,88,52,79,192,83,5,75,196,119
2004,1,162,124,12,1,126,58,123,186,161,...,100,93,86,12,115,72,29,30,88,150

#### 1.index '2001' 데이터(행)에서 평균보다 큰 값의 개수를 구하시오.

In [114]:
mean2001 = df.loc[2001].mean()
cond1 = df.loc[2001] > mean2001

print("2001 데이터 평균 초과의 개수 :", sum(cond1))

2001 데이터 평균 초과의 개수 : 100

#### 2.index '2003' 데이터(행)에서 평균보다 작은 값의 개수를 구하시오.

In [115]:
mean2003 = df.loc[2003].mean()
cond2 = df.loc[2003] < mean2003

print("2001 데이터 평균 미만의 개수 :", sum(cond2))

2001 데이터 평균 미만의 개수 : 102

#### 두 개수를 더하시오.

In [117]:
print('합계 :', sum(cond1) + sum(cond2))

합계 : 202

## S19.결측치(뒤의 값으로 대체), 그룹합

In [129]:
df = pd.read_csv('type1_data1.csv')
print("행 수 :", len(df))
df.head()

행 수 : 120

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.결측치를 바로 뒤에 있는 값으로 대체하시오.
#### (바로 뒤의 값도 결측치인 경우, 뒤에 있는 데이터 중 가장 가까운 값으로 대체)

In [130]:
df = df.bfill()
df.head()

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울  70.0   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1  gold  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울  85.0   2   vip  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   vip  ISFJ  29.269869  2024-03-07  1338.0

#### 2.'city'와 'f2' 컬럼을 기준으로 그룹합을 계산하시오.

In [131]:
df = df.groupby(['city','f2']).sum(numeric_only=True).reset_index()
df

   city  f2     age      f1           f5     views
0    경기   0  1192.9  1490.0  1425.236647  154066.0
1    경기   1   997.0  1016.0   935.958628   91442.0
2    경기   2   296.0   390.0   430.186433   42709.0
3    대구   0   664.0   982.0   371.184620  100421.0
4    대구   1   393.6   471.0   404.779978   49536.0
5    대구   2   185.0   321.0    79.667919   22624.0
6    부산   0   525.0   691.0   395.272907   80460.0
7    부산   1   475.7   684.0   460.657406   51624.0
8    부산   2    38.5   189.0   101.195372   17771.0
9    서울   0   241.0   480.0   484.809540   61447.0
10   서울   1   433.3   687.0   506.371383   59111.0
11   서울   2   165.3   337.0   179.328213   22405.0

#### 3.'views'값이 세 번째로 큰 city 이름을 구하시오.

In [133]:
df = df.sort_values('views', ascending=False)
df.head()

  city  f2     age      f1           f5     views
0   경기   0  1192.9  1490.0  1425.236647  154066.0
3   대구   0   664.0   982.0   371.184620  100421.0
1   경기   1   997.0  1016.0   935.958628   91442.0
6   부산   0   525.0   691.0   395.272907   80460.0
9   서울   0   241.0   480.0   484.809540   61447.0

In [135]:
print('3번째로 큰 도시명 :', df.iloc[2,0])

3번째로 큰 도시명 : 경기

## S20.시계열 데이터, 월별 집계, 인덱스

In [136]:
df = pd.read_csv('type1_data1.csv')
print("행 수 :", len(df))
df.head()

행 수 : 120

     id   age city    f1  f2    f3    f4         f5  subscribed   views
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791  2024-07-16  6820.0
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826  2024-05-12  2534.0
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986  2024-03-16  7312.0
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078  2024-07-21   493.0
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869  2024-03-07  1338.0

#### 1.연도 구분없이 월별로 숫자형 컬럼의 합을 구하시오.

In [137]:
df['subscribed'] = pd.to_datetime(df['subscribed'], format='%Y-%m-%d')
df['month'] = df['subscribed'].dt.month
df.head()

     id   age city    f1  f2    f3    f4         f5 subscribed   views  month
0  id01   2.0   서울   NaN   0  gold  ENFJ  91.297791 2024-07-16  6820.0      7
1  id02   9.0   서울  70.0   1   NaN  ENFJ  60.339826 2024-05-12  2534.0      5
2  id03  27.0   서울  61.0   1  gold  ISTJ  17.252986 2024-03-16  7312.0      3
3  id04  75.0   서울   NaN   2   NaN  INFP  52.667078 2024-07-21   493.0      7
4  id05  24.0   서울  85.0   2   NaN  ISFJ  29.269869 2024-03-07  1338.0      3

In [138]:
df = df.groupby(['month']).sum(numeric_only=True)
df.head()

         age      f1  f2          f5     views
month
1      441.8   608.0   1  487.453162   40013.0
2      860.7  1301.0  25  460.248156  165852.0
3      326.3   457.0   8  352.729057   39031.0
4      307.0   268.0   4  312.187975   41307.0
5      809.6   822.0  10  855.287894  110786.0

#### 합계 중 'views'가 가장 작은 값을 가진 월을 정수로 구하시오.

In [139]:
df = df.sort_values('views', ascending=True)
df.head()

         age     f1  f2          f5    views
month
11     186.0  181.0   1  278.410220  15857.0
12     365.0  373.0   2  515.672397  28658.0
6      481.8  244.0   6  387.206296  31295.0
3      326.3  457.0   8  352.729057  39031.0
1      441.8  608.0   1  487.453162  40013.0

In [140]:
print("views가 가장 작은 달 : ", df.index[0])

views가 가장 작은 달 :  11